# Generated by Django 5.0.6 on 2024-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omegameds',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
