# Generated by Django 5.0.6 on 2024-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0003_alter_omegameds_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omegameds',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
