# Generated by Django 5.0.6 on 2024-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0005_alter_omegameds_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='omegameds',
            name='read_more',
            field=models.CharField(blank='false', max_length=200),
        ),
    ]
