# Generated by Django 5.0.6 on 2024-07-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Omega', '0006_omegameds_read_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omegameds',
            name='read_more',
        ),
    ]
